<?php
namespace app\common\validate;
use think\Validate;

class Bis extends Validate
{
	protected $rule = [
		'name' => 'require|length:2,50',
		'city_id' => 'require|number',
		'logo' => 'require',
		'licence_logo' => 'require',
		'description' => 'require',
		'bank_info' => 'require',
		'bank_name' => 'require',
		'bank_user' => 'require',
		'faren' => 'require|length:2,6',
		'faren_tel' => 'require|length:11',
		'email' => 'require|email',
		'tel' => 'require|length:11',
		'contact' => 'require|length:2,6',
		'category_id' => 'require|number',
		'address' => 'require',
		'open_time' => 'require',
		'content' => 'require',
		'username' => 'require',
		'password' => 'require',

		'bis_id' => 'require|number',
		'location_ids' => 'require',
		'start_time' => 'require|number',
		'end_time' => 'require|number',
		'coupons_begin_time' => 'require|number',
		'coupons_end_time' => 'require|number',
		'origin_price' => 'require',
		'current_price' => 'require',
		'total_count' => 'require',
		'bis_account_id' => 'require|number',
		'notes' => 'require',
	];

	protected $message = [
		'name.require' => '商户名称必须填写！',
		'name.length' => '商户名称长度必须jx于50个字符！',
		'city_id' => '所属城市选择不合法！',
		'logo' => '缩略图必须上传！',
		'description' => '商户介绍必须填写！',
		'bank_info' => '银行账号必须填写！',
		'bank_name' => '开户行名称必须填写！',
		'licence_logo' => '营业执照必须上传！',
		'bank_user' => '开户行姓名必须填写！',
		'faren.require' => '法人必须填写！',
		'faren.length' => '法人名称长度非法！',
		'faren_tel.require' => '法人电话必须填写！',
		'faren_tel.length' => '法人电话长度非法！',
		'tel.require' => '电话必须填写！',
		'tel.length' => '电话长度非法！',
		'email.require' => '邮箱必须填写！',
		'email.email' => '邮箱格式非法！',
		'contact.require' => '联系人必须填写！',
		'contact.length' => '联系人长度非法！',
		'category_id' => '所属分类选择非法！',
		'address' => '地址必须填写！',
		'open_time' => '营业时间必须填写！',
		'username' => '用户名必须填写！',
		'password' => '密码必须填写！',
		'content' => '门店简介必须填写！',

		'bis_id' => '请求非法！',
		'location_ids' => '支持门店必须选择！',
		'start_time.require' => '团购开始时间必须填写',
		'start_time.number' => '团购开始时间非法！',
		'end_time.require' => '团购结束时间必须填写！',
		'end_time.number' => '团购结束时间非法！',
		'coupons_begin_time.require' => '消费券生效时间必须填写！',
		'coupons_begin_time.number' => '消费券生效时间非法！',
		'coupons_end_time.require' => '消费券结束时间必须填写！',
		'coupons_end_time.number' => '消费券结束时间非法！',
		'origin_price' => '原价必须填写！',
		'current_price' => '团购价必须填写！',
		'total_count' => '库存数必须填写！',
		'bis_account_id' => '请求非法！',
		'notes' => '购买须知必须填写',
	];

	protected $scene = [
		'add' => ['name','city_id','logo','description','bank_user','bank_name','bank_info','licence_logo',
				'faren','faren_tel','tel','email','contact','content','open_time','category_id','address',
				'username','password'],
		'bis' => ['name','city_id','logo','description','bank_user','bank_name','bank_info','licence_logo',
						'faren','faren_tel','email','category_id'],
		'location' => ['name','city_id','logo','contact','tel','content','open_time',
					'category_id','address',],
		'account' => ['username','password'],
		'deal' => ['name', 'image', 'bis_id', 'location_ids', 'start_time', 'end_time', 'coupons_begin_time',
					'coupons_end_time', 'description', 'city_id', 'category_id', 'origin_price', 
					'current_price', 'total_count', 'bis_account_id', 'notes'],
	];
}